title: Simon Zeng - Resume
author: Simon Zeng
description: 3rd-year Computer Science student seeking summer 2021 internship
email: contact@simonzeng.com
url: "https://simonzeng.com/resume"

plugins:
  - jekyll-feed
