name: CI

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install dhall
        uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.28.0'

      - name: Install xelatex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true

      - name: Install pandoc
        uses: Ender-events/pandoc@master

      - name: Make
        run: "cd zeng-simon-resume && make all"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zeng-simon-resume/target/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: zeng-simon-resume/target/ # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
